title: Site

tabs:
  content:
    columns:
      - width: 2/3
        sections:
          pages:
            type: pages
            layout: list
            image:
              query: false
            info: "Template: {{ page.template }}"
            create:
              - default
              - home
              - harvester
              - dataprotection
              - linkbush
            template:
              - default
              - harvester
              - home
              - dataprotection
              - linkbush
          privacy:
            type: fields
            label: Cookie Banner
            fields:
              bannertext:
                type: textarea
                label: Cookie Banner Text
                size: small
                buttons:
                  - bold
                  - italic
                  - '|'
                  - link
                  - email
              buttontext_allow:
                width: 1/2
                type: text
                label: Buttontext 'Zustimmung'
              buttontext_optout:
                width: 1/2
                type: text
                label: Buttontext 'Opt-out'

      - width: 1/3
        sections:
          janitor:
            type: fields
            fields:
              janitor:
                type: janitor
                label: Clean Cache
                progress: Cleaning Cache...
                job: cleanCache

          opening:
            type: fields
            fields:
              open:
                label: Austellung Eröffnet
                type: toggle
                width: 2/4

          footer:
            label: Footer
            type: fields
            fields:
              secrets:
                label: Kirby CMS Hinweise
                type: structure
                fields:
                  text:
                    type: textarea
                    buttons:
                      - bold
                      - italic
                      - '|'
                      - link

  exhibition:
    sections:
      exhibitions:
        type: pages
        layout: cards
        image:
          query: false
        info: "Template: {{ page.template }}"
        create:
          - exhibit
        template:
          - exhibit
