title: Site

tabs:
  content:
    columns:
      - width: 2/3
        sections:
          pages:
            type: pages
            layout: list
            image:
              query: false
            info: "Template: {{ page.template }}"
            create:
              - default
              - home
              - harvester
              - dataprotection
            template:
              - default
              - harvester
              - home
              - dataprotection
          privacy:
            type: fields
            label: Cookie Banner
            fields:
              bannertext:
                type: textarea
                label: Cookie Banner Text
                size: small
                buttons:
                  - bold
                  - italic
                  - '|'
                  - link
                  - email
              buttontext_allow:
                width: 1/2
                type: text
                label: Buttontext 'Zustimmung'
              buttontext_optout:
                width: 1/2
                type: text
                label: Buttontext 'Opt-out'

      - width: 1/3
        sections:
          footer:
            label: Footer
            type: fields
            fields:
              secrets:
                label: Kirby CMS Hinweise
                type: structure
                fields:
                  text:
                    type: textarea
                    buttons:
                      - bold
                      - italic
                      - '|'
                      - link
